linuxdeepin/dde-kwin

dde-kwin.pro, scripts/screenedge/closewindowaction/LICENSE, scripts/screenedge/closewindowaction/contents/main.js, scripts/screenedge/closewindowaction/metadata.desktop, scripts/screenedge/runcommandaction/LICENSE, scripts/screenedge/runcommandaction/contents/main.js, scripts/screenedge/runcommandaction/metadata.desktop, scripts/scripts.pro
Extended hot zone support:
* Close active window
* Custom command to exectue
eg(command): ~/.config/kwinrc
[Script-runcommandaction]
Border3Program=dde-control-center
Border3Args=--show
BorderActivate=3
=> feat: screen edget support "close active window"/"run custom command"

configures/kwin_no_scale
照顾没有给kglobalaccel打patch的kde环境。
=> refactor: try cp "kglobalshortcutsrc" on exec kwin before

scripts/ddelauncher/LICENSE, scripts/ddelauncher/contents/main.js, scripts/ddelauncher/metadata.desktop, scripts/scripts.pro
Force the dde-launcher window keep in screen area
=> feat: add the "dde-launcher" script

debian/control, plugins/kwin-xcb/lib/kwinutils.cpp, plugins/kwin-xcb/lib/kwinutils.h, plugins/kwin-xcb/lib/lib.pro, plugins/kwin-xcb/plugin/main.cpp, scripts/gtkframe/LICENSE, scripts/gtkframe/contents/main.js, scripts/gtkframe/metadata.desktop, scripts/scripts.pro
script name: GTK Window Frame
Contain the window gtk frame extents on maximize/fullscreen
=> feat: add kwin script

dde-kwin.pro, debian/control, deepin-wm-dbus/com_deepin_wm.xml, deepin-wm-dbus/deepin-wm-dbus.pro, deepin-wm-dbus/deepinwmfaker.cpp, deepin-wm-dbus/deepinwmfaker.h, deepin-wm-dbus/main.cpp
在 kwin 下模拟 deepin-wm 的一些 dbus 接口供上层应用使用，相关 issue：
https://github.com/linuxdeepin/internal-discussion/issues/1146
=> feat: add dbus interface of old deepin wm

deepin-wm-dbus/com.deepin.wm.xml.in, deepin-wm-dbus/deepinwmfaker.cpp, deepin-wm-dbus/deepinwmfaker.h, plugins/kwin-xcb/lib/kwinutils.cpp, plugins/kwin-xcb/lib/kwinutils.h, plugins/kwin-xcb/plugin/org.kde.kwin.KWinUtils.xml
ToggleActiveWindowMaximimze and MinimizeActiveWindow
=> feat: implemention two actions of PerformAction

configures/kwinrc
=> feat: set default tasks switch manager

debian/control, plugins/kwin-xcb/lib/kwinutils.cpp, plugins/kwin-xcb/lib/kwinutils.h, plugins/kwin-xcb/lib/lib.pro, plugins/kwin-xcb/plugin/main.cpp
=> feat: add show workspaces manager view interface

deepin-wm-dbus/deepinwmfaker.cpp, deepin-wm-dbus/deepinwmfaker.h, scripts/screenedge/runcommandaction/contents/main.js
=> fix: zone setting is invalid

aurorae-themes/deepin/metadata.desktop, deepin-wm-dbus/com.deepin.wm.xml.in, deepin-wm-dbus/deepinwmfaker.cpp, deepin-wm-dbus/deepinwmfaker.h
支持设置窗口标题栏主题。
@electricface 后端适配一下
com.deepin.wm /com/deepin/wm com.deepin.wm.SetDecorationDeepinTheme
light 为白色主题
dark 为黑色主题
=> feat: support set window decoration theme

deepin-wm-dbus/deepinwmfaker.cpp
=> fix: delete old action before setting the zone

configures/kwinrc, dde-kwin.pro, debian/dde-kwin.install, tabbox/tabbox.pro, tabbox/thumbnail_grid/contents/ui/main.qml, tabbox/thumbnail_grid/metadata.desktop
set the "thumbnail_grid" to tabbox default theme
添加一个默认的窗口切换主题包
=> feat: add a new tabbox theme

deepin-wm-dbus/com.deepin.wm.xml.in, deepin-wm-dbus/deepinwmfaker.cpp, deepin-wm-dbus/deepinwmfaker.h, plugins/kwin-xcb/lib/kwinutils.cpp, plugins/kwin-xcb/lib/kwinutils.h, plugins/kwin-xcb/plugin/main.cpp, plugins/kwin-xcb/plugin/org.kde.kwin.KWinUtils.xml
Re-login when the compositing is closed
修复关闭窗口特效后注销重进系统无法开启特效
@electricface
=> fix: can not enable compositing for kwin

deepin-wm-dbus/com.deepin.wm.xml.in, deepin-wm-dbus/deepinwmfaker.cpp, deepin-wm-dbus/deepinwmfaker.h, scripts/screenedge/closewindowaction/contents/main.js, scripts/screenedge/runcommandaction/contents/main.js
compatibility deepin-wm interfaces:
* EnableZoneDetected
添加控制热区功能是否开启的接口，且兼容deepin-wm的定义
=> feat: support set the zone enabled property

plugins/kwin-xcb/lib/lib.pro
=> fix: build failed on libkf5windowsystem-dev 5.28.0

plugins/kwin-xcb/plugin/main.cpp
=> feat: support wait kwin started on startdde

deepin-wm-dbus/deepinwmfaker.cpp
https://github.com/linuxdeepin/internal-discussion/issues/1310
=> fix: transform all sign keys

configures/kwinrc
https://github.com/linuxdeepin/internal-discussion/issues/1343
=> disable kwin4_effect_dialogparentEnabled

debian/control
* qml-module-qtquick-controls2
* qml-module-qtquick-templates2
修复iso中工作区界面不显示 移除/添加 按钮
=> fix: add depends for kwin

configures/kwin_no_scale, plugins/kwin-xcb/plugin/main.cpp
https://github.com/linuxdeepin/internal-discussion/issues/1337
kwin 崩溃重启时使用 kwin_no_scale 脚本重启自己
=> fix: start kwin_no_scale when the kwin restart with crash

configures/configures.pro, configures/klaunchrc, configures/kwinrc
disable kwin4_effect_translucency
disable kwin4_effect_windowaperture
https://github.com/linuxdeepin/internal-discussion/issues/1244
https://github.com/linuxdeepin/internal-discussion/issues/1329
禁用kwin启动应用时的光标动画
禁用kwin移动窗口时的半透明效果
禁用kwin显示桌面时四个角的窗口缩略图效果
=> refactor: disable busy cursor

deepin-wm-dbus/com.deepin.wm.xml.in, deepin-wm-dbus/deepinwmfaker.cpp, deepin-wm-dbus/deepinwmfaker.h, plugins/kwin-xcb/lib/kwinutils.cpp, plugins/kwin-xcb/lib/kwinutils.h, plugins/kwin-xcb/plugin/main.cpp
=> feat: support set cursor theme/size for kwin

plugins/kwin-xcb/lib/kwinutils.cpp
使用 qt_linux_find_symbol_sys 直接加载kwin函数符号，避免执行库文件加载动作
=> refactor: use the qt_linux_find_symbol_sys resolve kwin symbol

deepin-wm-dbus/com.deepin.wm.xml.in, deepin-wm-dbus/deepinwmfaker.cpp, deepin-wm-dbus/deepinwmfaker.h
=> feat: support PresentWindows

deepin-wm-dbus/deepinwmfaker.cpp
See: https://github.com/linuxdeepin/deepin-kwin/pull/15
优先使用kwin中提供的窗口预览接口
=> feat: preview window give priority to use the dbus interface by kwin

configures/kdeglobals
禁用kwin的窗口菜单。后期会改成使用dbus menu显示deepin风格的窗口菜单
=> feat: disable window manager window menu

plugins/kwin-xcb/lib/kwinutils.cpp, plugins/kwin-xcb/lib/kwinutils.h, plugins/kwin-xcb/lib/lib.pro
feat: Support link the libkwin.so on build
https://github.com/linuxdeepin/developer-center/issues/1103
https://github.com/linuxdeepin/developer-center/issues/1163
支持打包脚本中控制kwin版本号，以及支持控制是否链接libkwin
=> feat: Support for specifying the version of kwin on build

.tx/config, configures/configures.pro, configures/kdeglobals, configures/kwin_no_scale, configures/kwin_no_scale.in, debian/control, debian/dde-kwin.install, plugins/kwin-xcb/lib/kwinutils.cpp, plugins/kwin-xcb/lib/kwinutils.h, plugins/kwin-xcb/plugin/libkwinpreload.cpp, plugins/kwin-xcb/plugin/libkwinpreload.h, plugins/kwin-xcb/plugin/main.cpp, plugins/kwin-xcb/plugin/plugin.pro, plugins/kwin-xcb/plugin/translate_generation.sh, plugins/kwin-xcb/plugin/translations/dde-kwin-xcb.ts
覆盖kwin的窗口菜单，支持使用deepin样式的QMenu，或者使用deepin dbus menu，默认不使用dbus menu
=> feat: the window menu use deepin dbus menu

deepin-wm-dbus/deepinwmfaker.cpp
在非deepin-kwin环境中优先使用kwin自带的窗口预览特效。kwin的窗口预览特效不支持2D模式，因此不会将其作为deepin-kwin的默认实现
=> feat: support KWin highlightWindows effect for PreviewWindow

configures/kwinrc
Fix the minimized windows no preview on dock
https://github.com/linuxdeepin/internal-discussion/issues/1615
=> fix: keep window to viewable if it is minimized

configures/kwinrc
fix window can't take focus sametimes
=> refactor: set the "FocusStealingPreventionLevel" config to 0

plugins/kwin-xcb/plugin/main.cpp
=> fix: clean LD_PRELOAD env

configures/kwinrc
=> refactor: disable HideUtilityWindowsForInactive of kwin

plugins/kwin-xcb/plugin/main.cpp
https://github.com/linuxdeepin/internal-discussion/issues/1698
修复窗口菜单没有加载翻译
=> fix: correct the path to find translation files

plugins/CMakeLists.txt, plugins/kdecoration/CMakeLists.txt, plugins/kdecoration/chameleon.cpp, plugins/kdecoration/chameleon.h, plugins/kdecoration/chameleonshadow.cpp, plugins/kwin-xcb/lib/kwinutils.cpp, plugins/kwin-xcb/lib/kwinutils.h, plugins/kwineffects/CMakeLists.txt, plugins/kwineffects/scissor-window/CMakeLists.txt, plugins/kwineffects/scissor-window/cornermask.frag.110, plugins/kwineffects/scissor-window/cornermask.frag.140, plugins/kwineffects/scissor-window/fullmask.frag.110, plugins/kwineffects/scissor-window/fullmask.frag.140, plugins/kwineffects/scissor-window/glsl.qrc, plugins/kwineffects/scissor-window/main.cpp, plugins/kwineffects/scissor-window/scissor-window.json, plugins/kwineffects/scissor-window/scissorwindow.cpp, plugins/kwineffects/scissor-window/scissorwindow.h
Support set radius of anything window
支持为窗口设置圆角特效
=> feat: add window effects

plugins/kwin-xcb/lib/kwinutils.cpp, plugins/kwin-xcb/lib/kwinutils.h
=> feat: support set window propertys on X11 platform

plugins/kdecoration/CMakeLists.txt, plugins/kdecoration/chameleon.cpp, plugins/kdecoration/chameleon.h, plugins/kdecoration/chameleonconfig.cpp, plugins/kdecoration/chameleonconfig.h, plugins/kdecoration/chameleonshadow.cpp, plugins/kdecoration/chameleonshadow.h, plugins/kwin-xcb/lib/kwinutils.cpp, plugins/kwin-xcb/lib/kwinutils.h, plugins/kwin-xcb/plugin/main.cpp
=> feat: add shadow image for no border windows

plugins/kwineffects/scissor-window/scissorwindow.cpp
通过窗口绘制区域判断是否处于圆角部位，将窗口的圆角及非圆角区域分开渲染
修复支持alpha通道的窗口未绘制窗口内容
=> refactor: optimize window radius render

plugins/kdecoration/chameleon.cpp, plugins/kdecoration/chameleon.h, plugins/kdecoration/chameleonconfig.cpp, plugins/kdecoration/chameleonconfig.h, plugins/kwin-xcb/lib/kwinutils.cpp, plugins/kwin-xcb/lib/kwinutils.h
=> feat: support set window no titlebar

configures/kwinrc
Disable the effects follow:
kwin4_effect_fadeEnabled=false
kwin4_effect_loginEnabled=false
kwin4_effect_morphingpopupsEnabled=false
slidingpopupsEnabled=false
zoomEnabled=false
=> refactor: adjust kwin animation speed to very first

plugins/kdecoration/chameleon.cpp, plugins/kdecoration/chameleon.h, plugins/kdecoration/chameleonconfig.cpp, plugins/kdecoration/chameleonshadow.cpp
fix custom window border invalid on 2D mode
修复窗口边框不明显
修复自定义边框和阴影的颜色无效。
=> fix: make the border of the window look cleaner and clear

plugins/kdecoration/chameleonconfig.cpp, plugins/kdecoration/chameleontheme.cpp, plugins/kwin-xcb/lib/kwinutils.h
eg: Desktop Dock TopMenu Splash Notification OnScreenDisplay
=> fix: manage shadow and window radius for special types of windows

plugins/kdecoration/chameleonconfig.cpp, plugins/kdecoration/chameleonshadow.cpp, plugins/kdecoration/deepin/dark/decoration.ini, plugins/kdecoration/deepin/light/decoration.ini
fix shadow size
修复窗口阴影大小错误已经阴影没有跟随窗口主题设置属性变动进行更新
=> fix: update window shadow when the window theme properties changed

plugins/kdecoration/chameleonshadow.cpp
=> fix: enable QPainter::Antialiasing with draw window border

CMakeLists.txt, configures/kwinrc, debian/control, plugins/kwin-xcb/lib/CMakeLists.txt, plugins/kwineffects/CMakeLists.txt, plugins/kwineffects/blur/CMakeLists.txt, plugins/kwineffects/blur/blur.cpp, plugins/kwineffects/blur/blur.h, plugins/kwineffects/blur/blur.json, plugins/kwineffects/blur/blurshader.cpp, plugins/kwineffects/blur/blurshader.h, plugins/kwineffects/blur/main.cpp
=> feat: add window blur effect

plugins/kwineffects/blur/blur.cpp
kf5 does not inherit Global and has no create method.
Log:
Issue: Closes #127
=> fix: blurmanager interface changed

plugins/kwineffects/blur/blur.cpp, plugins/kwineffects/blur/blur.h, plugins/kwineffects/multitasking/CMakeLists.txt, plugins/kwineffects/multitasking/multitasking.cpp, plugins/kwineffects/multitasking/multitasking.h, plugins/platforms/lib/kwinutils.h
KWayandServer::Display::BlurManager need KWaylandServer::BlurManagerInterface
Issue: Closes #136
Issue: Closes #47
Log:
=> fix: Doesn't compile with Kwin 5.21

tests/CMakeLists.txt
missing include platform/lib
Log:
=> fix: missing include header

.reuse/dep5, README.md, README.zh_CN.md, debian/changelog
Added documentation 'README.md' and 'README.zh_CN.
=> doc: Added documentation 'README.md' and 'README.zh_CN.

configures/kwinrc, debian/changelog, deepin-wm-dbus/com.deepin.wm.xml.in, deepin-wm-dbus/deepinwmfaker.cpp, deepin-wm-dbus/deepinwmfaker.h, plugins/kdecoration/chameleonbutton.cpp, plugins/kwineffects/blur/blur.cpp
=> Topic graphics eagle 20221221

deepin-wm-dbus/CMakeLists.txt
=> chore: update dtkcore

debian/changelog
update changelog
Log: update changelog
Task: linuxdeepin/developer-center#3530
Influence: obs build
=> fix: add missing blank in debian/changelog
